language: generic
sudo: required
dist: trusty

env:
    - QGIS_REPO=http://qgis.org/debian-ltr

addons:
  apt:
    packages:
      - python-software-properties
      - libhdf5-serial-dev
      - libnetcdf-dev
      - xvfb  # emulating X-server
      - pyqt4-dev-tools

before_install:
    - sudo apt-get -qq -y update

install:
    # See: https://github.com/tomchadwin/qgis2web/blob/master/.travis.yml
    - sudo add-apt-repository ${QGIS_REPO}
    - sudo apt-get update
    - sudo apt-get install -y --force-yes qgis python-qgis
    # linux requirements
    - sudo pip install -r requirements-dev.txt
    # required pure python packages
    - pip install -r requirements.txt --target=external --no-deps

script:
    - xvfb-run make test
    - make pep8

notifications:
    email: false

cache:
    directories:
    - $HOME/.cache/pip
